name: Package Updates
on:
  workflow_dispatch: ~
  schedule:
    - cron: 0 10 * * 1 # 10am UTC every Monday

jobs:
  open-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.8.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm update-all
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          title: Update all package dependencies
          body: |
            All package dependencies, automatically updated by `ncu`.
          commit-message: Update all package dependencies
          author: icon-bot <67597316+icon-bot@users.noreply.github.com>
          commiter: icon-bot <67597316+icon-bot@users.noreply.github.com>
          delete-branch: 'true'
          branch: icon-bot/package-updates
